# Docker Compose Base - Sin base de datos
version: '3.8'

services:
  # Frontend - Next.js
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:3001/api}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend - NestJS
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@localhost:5432/mydatabase}
      - USE_LOCAL_DB=${USE_LOCAL_DB:-false}
      - PORT=3001
    volumes:
      - api-uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  api-uploads:
    driver: local

networks:
  app-network:
    driver: bridge
